# -*- coding: utf-8 -*-
"""Proyek Analisis Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cvsWArn8lODf4iMW44juq65zQFTLiqQd

# Proyek Analisis Data: Air Quality Dataset - Huairou Station
- **Nama:** Istia Budi
- **Email:** istiabudi@gmail.com
- **ID Dicoding:** istiabudi73

## Menentukan Pertanyaan Bisnis

- Bagaimana kondisi materi partikulat PM(2.5) dan PM(10) yang dimonitoring pada stasiun Huairou.
- Apakah jam sibuk mempengaruhi polusi udara dibanding tengah malam.
- Apakah hujan (RAIN) memiliki efek dalam mengurangi polusi udara?

## Import Semua Packages/Library yang Digunakan
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""## Data Wrangling

### Gathering Data
"""

huairou_df = pd.read_csv('PRSA_Data_Huairou_20130301-20170228.csv')
huairou_df

"""**Insight:**
- [Air Quality Dataset](https://drive.google.com/file/d/1RhU3gJlkteaAQfyn9XOVAz7a5o1-etgr/view) adalah kumpulan data tentang polusi udara di Beijing, China, yang dikumpulkan dari berbagai stasiun pemantauan kualitas udara. Pada proyek ini data hasil pemantauan kualitas udara yang berasal dari stasiun Huairou akan digunakan untuk melakukan analisis data.
- Pemantauan kualitas udara dilakukan dalam rentang 1 Maret 2013 hingga 28 Februari 2017.
- Dataset ini memiliki 35064 baris dan 18 kolom.

### Assessing Data
"""

huairou_df.info()

"""### Cleaning Data

Check missing values
"""

huairou_df.isnull().sum()

"""Remove missing values"""

huaioru_df = huairou_df.dropna()
len(huaioru_df)

"""Check duplication data"""

huairou_df.duplicated().sum()

"""Check parameter statistik"""

huairou_df.describe()

"""Check outlier"""

column_to_check = huairou_df[['PM2.5', 'PM10', 'SO2', 'NO2', 'CO', 'O3']]
plt.figure(figsize=(12, 6))
sns.boxplot(data=column_to_check)
plt.yscale('log')
plt.title('Boxplot deteksi outlier')
plt.show()

"""Remove outlier dengan IQR (Interquantile Range)"""

for col in column_to_check:
    Q1 = huairou_df[col].quantile(0.25)
    Q3 = huairou_df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    huairou_df = huairou_df[(huairou_df[col] >= lower_bound) & (huairou_df[col] <= upper_bound)]

huairou_df

huairou_df.describe()

"""**Insight:**
- Terdapat 3356 baris data yang memiliki data kosong. Karena datanya 35064 jadi perubahan datanya tidak terlalu signifikan
- Tidak ada data duplikasi pada dataset ini
- Membersihkan outlier pada kolom PM2.5, PM10, SO2, NO2, CO, O3 karena banyaknya data tidak wajar.
"""

huaioru_df.to_csv('data.csv', index=False)

"""## Exploratory Data Analysis (EDA)

### Eksplorasi Data Stasiun Huairou

Statistik Deskriptif
"""

huairou_df.describe(include='all')

"""Check distribusi data"""

numerical_columns = huaioru_df.select_dtypes(include=['float64', 'int64']).columns
for col in numerical_columns:
    plt.figure(figsize=(12, 6))
    sns.histplot(huairou_df[col], kde=True, bins=30, color='blue')
    plt.title(f'Distribusi: {col}')
    plt.xlabel(col)
    plt.ylabel('Frekuensi')
    plt.show()

"""**Insight:**
- ```PM(2.5)```: Distribusi Miring ke Kanan, Pola ini menunjukkan bahwa konsentrasi partikel halus di udara umumnya dalam batas aman, tetapi terdapat periode di mana jumlahnya meningkat tajam. Partikel halus ini sangat berbahaya karena dapat masuk ke dalam sistem pernapasan manusia dan sering kali meningkat akibat pembakaran bahan bakar dan aktivitas industri.
- ```PM(10)```: Distribusi Miring ke Kanan, Data ini mengindikasikan bahwa kualitas udara sebagian besar berada pada kondisi normal, tetapi terdapat hari-hari tertentu dengan tingkat polusi udara yang lebih tinggi. Peningkatan konsentrasi partikel debu kasar ini dapat terjadi akibat aktivitas kendaraan, konstruksi, atau kondisi cuaca seperti angin kencang.
- ```SO2```: Distribusi Sangat Miring ke Kanan, Artinya, sebagian besar nilai SO₂ rendah, tetapi ada beberapa lonjakan sangat tinggi. SO₂ biasanya berasal dari pembakaran batu bara atau aktivitas industri, jadi lonjakan ini bisa terjadi saat ada aktivitas industri yang tinggi dalam periode tertentu.
- ```NO2```: Distribusi Miring ke Kanan, sebagian besar data berada di nilai rendah tetapi ada beberapa nilai yang cukup tinggi. NO₂ sering berasal dari emisi kendaraan dan aktivitas industri, sehingga kemungkinan ada periode di mana aktivitas ini lebih tinggi dan menyebabkan lonjakan kadar NO₂.
- ```CO```: Distribusi Miring ke Kanan, Sebagian besar nilai CO rendah, tetapi ada beberapa lonjakan tinggi, yang mungkin terjadi saat ada aktivitas industri atau transportasi tinggi. Karbon monoksida biasanya berasal dari kendaraan bermotor dan pembakaran bahan bakar, jadi bisa jadi ada waktu tertentu (misalnya jam sibuk) di mana kadarnya meningkat drastis.
- ```O3```: Distribusi Hampir Merata, Sedikit Miring ke Kanan, Artinya, konsentrasi ozon bervariasi tetapi ada beberapa nilai yang lebih tinggi dari biasanya.
- ```TEMP```: Distribusi Bimodal (Dua Puncak), Ini berarti ada dua kelompok utama suhu dalam dataset ini, kemungkinan besar disebabkan oleh perbedaan antara musim panas dan musim dingin. Bisa juga dipengaruhi oleh waktu siang dan malam, di mana suhu lebih tinggi di siang hari dan lebih rendah di malam hari.
- ```PRES```:  Distribusi Hampir Normal (Mirip Gunung - Simetris di Tengahnya), Ini menunjukkan bahwa tekanan udara cenderung stabil dan tidak banyak mengalami perubahan ekstrem. Biasanya, distribusi normal ini menandakan bahwa tekanan udara dalam kondisi wajar tanpa ada kejadian cuaca ekstrem yang sering terjadi.
- ```DEWP```: Distribusi Bimodal (Dua Puncak), Artinya, ada dua kelompok utama dalam data ini. Bisa jadi ada dua musim yang sangat berbeda, misalnya musim kemarau dengan curah hujan rendah dan musim hujan dengan curah hujan tinggi. Kemungkinan juga bisa disebabkan oleh pola hujan yang tidak merata sepanjang tahun.
- ```WSPM```: Distribusi Miring ke Kanan (Right-Skewed), Artinya, sebagian besar data memiliki nilai kecil, tetapi ada beberapa nilai yang sangat tinggi.  Kemungkinan ada beberapa periode di mana polusi udara meningkat tajam, mungkin akibat aktivitas manusia seperti pembakaran bahan bakar atau cuaca tertentu.


"""

numerical_df = huaioru_df.select_dtypes(include=['number'])

plt.figure(figsize=(12,6))
corr_matrix = numerical_df.corr()
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt='.2f')
plt.title('Korelasi Antar Variabel')
plt.show()

"""**Insight:**

Korelasi antar variabel menunjukkan bahwa PM2.5 dan PM10 memiliki hubungan kuat dengan polutan lain seperti CO dan NO2, yang umumnya berasal dari kendaraan dan industri. Ozon (O3) menunjukkan pola kebalikan dengan NO2 dan CO, karena terbentuk melalui reaksi fotokimia di udara. Dengan memahami hubungan ini, strategi pengendalian polusi dapat difokuskan pada pengurangan emisi dan pemanfaatan faktor lingkungan untuk meningkatkan kualitas udara.

## Visualization & Explanatory Analysis

### Pertanyaan 1:Bagaimana kondisi materi partikulat PM(2.5) dan PM(10) yang dimonitoring pada stasiun Huairou tiap tahun.
"""

yearly_avg = huairou_df.groupby('year')[['PM2.5', 'PM10']].mean()

# Plot grafik tren tahunan
plt.figure(figsize=(10, 5))
sns.lineplot(data=yearly_avg, markers=True)
plt.title("Tren Tahunan PM₂.₅ dan PM₁₀ di Stasiun Huairou")
plt.xlabel("Tahun")
plt.ylabel("Konsentrasi (µg/m³)")
plt.legend(["PM₂.₅", "PM₁₀"])
plt.grid(True)
plt.show()

"""### Pertanyaan 2: Apakah jam sibuk mempengaruhi polusi udara dibanding tengah malam"""

rush_hour_morning = huaioru_df[(huaioru_df['hour'] >= 7) & (huaioru_df['hour'] <= 9)]
rush_hour_evening = huaioru_df[(huaioru_df['hour'] >= 17) & (huaioru_df['hour']) <=19]
midnight = huaioru_df[(huaioru_df['hour'] >= 0) & (huaioru_df['hour']) <=4]

huaioru_df['time_category'] = 'Other'
huaioru_df.loc[huaioru_df['hour'].between(7, 9), 'time_category'] = 'Rush Hour (Morning)'
huaioru_df.loc[huaioru_df['hour'].between(17, 19), 'time_category'] = 'Rush Hour (Evening)'
huaioru_df.loc[huaioru_df['hour'].between(0, 4), 'time_category'] = 'Midnight'

plt.figure(figsize=(12, 6))
sns.histplot(data=huaioru_df, x='PM2.5', hue='time_category', bins=30, kde=True, palette='coolwarm', element='step', common_norm=False)
plt.title('Distribusi PM2.5 pada Jam Sibuk vs Tengah Malam')
plt.xlabel('Konsentrasi PM2.5 (µg/m³)')
plt.ylabel('Frekuensi')
plt.grid(True)
plt.show()

rush_hour_morning = huaioru_df[(huaioru_df['hour'] >= 7) & (huaioru_df['hour'] <= 9)]
rush_hour_evening = huaioru_df[(huaioru_df['hour'] >= 17) & (huaioru_df['hour']) <=19]
midnight = huaioru_df[(huaioru_df['hour'] >= 0) & (huaioru_df['hour']) <=4]

huaioru_df['time_category'] = 'Other'
huaioru_df.loc[huaioru_df['hour'].between(7, 9), 'time_category'] = 'Rush Hour (Morning)'
huaioru_df.loc[huaioru_df['hour'].between(17, 19), 'time_category'] = 'Rush Hour (Evening)'
huaioru_df.loc[huaioru_df['hour'].between(0, 4), 'time_category'] = 'Midnight'

plt.figure(figsize=(12, 6))
sns.histplot(data=huaioru_df, x='PM10', hue='time_category', bins=30, kde=True, palette='coolwarm', element='step', common_norm=False)
plt.title('Distribusi PM10 pada Jam Sibuk vs Tengah Malam')
plt.xlabel('Konsentrasi PM10 (µg/m³)')
plt.ylabel('Frekuensi')
plt.grid(True)
plt.show()

"""## Conclusion

- Bagaimana kondisi materi partikulat PM(2.5) dan PM(10) yang dimonitoring pada stasiun Huairou?

Kondisi materi partikulat yang dimonitoring pada stasiun Huairou dalam rentang 1 Maret 2013 hingga 28 Februari 2017 mengalami penurunan yang cukup baik. Artinya pemerintah Beijing cukup baik dalam melakukan mengurangi polusi udara.

- Apakah jam sibuk mempengaruhi polusi udara dibanding tengah malam?

Jam sibuk tidak selalu meningkatkan polusi udara secara signifikan, karena distribusi Midnight dan Other masih cukup tinggi. Sumber polusi lain selain kendaraan mungkin lebih dominan, seperti aktivitas industri atau kondisi cuaca yang menyebabkan akumulasi polutan. Sebagian besar polusi udara berada di level rendah, tetapi ada outlier tinggi yang bisa disebabkan oleh faktor ekstrem.
"""